sudo: 
  false


language: 
  c 

services:
  - docker

# # # Caching so the next build will be fast too.
# cache:
#   directories:
#   - $HOME/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh

script:
  - stack build
