sudo: 
  false


language: 
  c 

services:
  - docker

# # # Caching so the next build will be fast too.
# cache:
#   directories:
#   - $HOME/.stack

script:
#  - make build
#  - make run_travis
  - ls -lsA
